FactoryGirl.define do
  factory :college do
    name "University of Iowa"
    college_type "Public"
    city "Iowa City"
    state "Iowa"
    region "Town"
    student_body_size "25000"
    twitter "@IowaAdmissions"
    facebook "/IowaAdmissions"
    instagram "UofIAdmissions"
    admissions_rep_page "www.iowa.com/admissions"
    college_visit_page "www.iowa.com/college-visit"
    avg_gpa "3.3"
    avg_act "25"
    avg_sat "1360"
    percent_male "52"
    percent_female "48"
    percent_minority "11"
    percent_international "8"
    popular_majors "Business Management, Pre-Law, Anthropology"
    number_of_essays "2"
    number_of_recommendations "3"
    fall_deadline "June 1"
    early_admissions_deadline "November 15"
    in_state_tuition "12000"
    out_of_state_tuition "24000"
    percent_receive_financial_aid "65"
    notable_alumni "Ashton Kutcher"
  end
end
