FactoryGirl.define do
  factory :college do
    name "MyString"
type ""
city "MyString"
state "MyString"
region "MyString"
student_body_size "MyString"
twitter "MyString"
facebook "MyString"
instagram "MyString"
admissions_rep_page "MyString"
college_visit_page "MyString"
avg_gpa "MyString"
avg_act "MyString"
avg_sat "MyString"
percent_male "MyString"
percent_female "MyString"
percent_minority "MyString"
percent_international "MyString"
popular_majors "MyText"
number_of_essays "MyString"
number_of_recommendations "MyString"
spring_deadine "MyString"
summer_deadline "MyString"
fall_deadline "MyString"
early_admissions_deadline "MyString"
in_state_tuition "MyString"
out_of_state_tuition "MyString"
percent_receive_financial_aid "MyString"
notable_alumni "MyText"
  end

end
